# Generated by Django 4.0.6 on 2022-07-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_python'),
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='lastest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
            ],
        ),
    ]
